name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jrasanen/check-endpoint@v1.0.0
        with:
          url: https://purushoa-pokedex.onrender.com
          timeout: 10000