name: Periodic Health Check

on:
  schedule:
    # Runs at 00:00 every day
    - cron: '0 0 * * *'
  workflow_dispatch: # This button allows you to run it manually!

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jrasanen/check-endpoint@v1.0.0
        with:
          url: https://purushoa-pokedex.onrender.com/health
          timeout: 20000