name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day. Adjust as needed.

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jcmrob/url-health-check@v1
        with:
          url: https://purushoa-pokedex.onrender.com
          max-attempts: 3
          retry-delay: 5s
