name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx eslint "**/*.{js,jsx}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build

  deploy:
    needs: [lint, build]
    # This ensures deployment only happens on push to main, NOT on PRs, and not if #skip is used
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"

  notify_success:
    needs: [ deploy ]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Test Discord Webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: "Deployment Successful! Pokedex is live."
          webhookUrl: ${{ secrets.MY_NEW_WEBHOOK }}
  notify_failure:
    needs: [lint, build, deploy]
    # Runs if any of the required jobs above fail
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send failure notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: "❌ Build or Deployment failed! Check the logs here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}