name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx eslint "**/*.{js,jsx}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build

  deploy:
    needs: [lint, build]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"

  notify_success:
    needs: [ deploy ]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Send success notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Hello Discord! Phonebook deployment worked!"

  notify_failure:
    needs: [lint, build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send failure notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "❌ Phonebook-CICD: Build or Deployment failed! Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"